# This is a basic workflow to help you get started with Actions

name: action_histo_workflow

# Controls when the action will run. 
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
  main:
    name: run_workflow
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Test workflow
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Download miniconda and install dependencies
        run: |
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
          bash ~/miniconda.sh -b
          export PATH=~/miniconda3/bin:$PATH
          conda update --yes conda
          
